### ISSUE TITLE
A Get the Weather App

### ISSUE THREAD

**Issue by rahulshah456** [Sid200026/studious-train#8]
I want to push for both modifications 
1. Show user current temperature, time of the city
2. Improve UI

**Comment by Sid200026** [comment]
Go ahead @rahulshah456

**Comment by rahulshah456** [comment]
@Sid200026,  I want to change how the weather data is accessed through API by simplifying it with integrating the retrofit Library.
So what your suggestion?

**Comment by Sid200026** [comment]
I read about the retrofit library and from a quick look it looks like a great library to deal with APIs. You can go ahead and implement the app in this library @rahulshah456

**Comment by Sid200026** [comment]
I will be closing this issue because a PR related to this issue has been merged

**Comment by rahulshah456** [comment]
but 2. UI Improve is not done yet...

**Comment by Sid200026** [comment]
Ok...I though the PR was also related to change in UI but go ahead @rahulshah456 ....
All the best

**Comment by rahulshah456** [comment]
My PR status in hactoberfest is not updating even after merged, is anything I missed?

**Comment by Sid200026** [comment]
It should update....check now @rahulshah456
